
最后，探索一些测试异步代码的技术。本节中显示的示例需要 GoogleTest 和 Google Test Mock (gMock) 库才能编译。如果不熟悉这些库，请查看官方文档以了解如何安装和使用它们。

单元测试是一种编写小型独立测试的做法，用于验证单个代码单元的功能和行为。单元测试有助于查找和修复错误、重构和提高代码质量、记录和传达底层代码设计，以及促进协作和集成。

本节不会介绍将测试分组为逻辑和描述性套件的最佳方法，也不会介绍何时应使用断言或期望来验证不同变量的值和测试方法结果。本节的目的是提供一些有关如何创建单元测试来测试异步代码的指南，所以最好具备一些有关单元测试或测试驱动开发 (TDD) 的先前知识。

处理异步代码时的主要困难是，可能在另一个线程中执行，并且通常不知道何时发生或何时完成。

测试异步代码时要遵循的主要方法是尝试将功能与多线程分离，所以希望以同步方式测试异步代码，尝试在一个特定线程中执行它，删除上下文切换，线程创建和销毁，以及其他可能影响测试结果和时间的活动。有时也会使用计时器，等待在超时之前调用回调。

\mySubsubsection{12.3.1.}{测试简单的异步函数}

从测试异步操作的一个小例子开始。此示例展示了一个 asyncFunc() 函数，通过使用std::async 异步运行该函数进行测试：

\begin{cpp}
#include <gtest/gtest.h>
#include <chrono>
#include <future>

using namespace std::chrono_literals;

int asyncFunc() {
    std::this_thread::sleep_for(100ms);
    return 42;
}

TEST(AsyncTests, TestHandleAsyncOperation) {
    std::future<int> result = std::async(
                            std::launch::async,
                            asyncFunc);
    EXPECT_EQ(result.get(), 42);
}


int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

std::async 返回一个用于检索计算值的未来。本例中，asyncFunc 只需等待 100 毫秒即可返回值 42。如果异步任务正常运行，则测试将通过，因为有一个期望指令检查返回值是否确实是 42。

只定义了一个测试，使用 TEST() 宏，其中其第一个参数是测试套件名称（在此示例中为 AsyncTests），第二个参数是测试名称（TestHandleAsyncOperation）。

在 main() 函数中，通过调用 ::testing::InitGoogleTest() 初始化 GoogleTest 库。此函数解析命令行以获取 GoogleTest 识别的标志。调用 RUN\_ALL\_TESTS()，收集并运行所有测试，如果所有测试都成功，则返回 0，否则返回 1。此函数最初是一个宏，这就是其名称大写的原因。

\mySubsubsection{12.3.2.}{使用超时限制测试持续时间}

这种方法可能出现的一个问题是，异步任务可能因任何原因而无法安排，完成时间可能比预期的要长，或者由于某些原因而无法完成。为了处理这种情况，可以使用计时器，将其超时时间设置为合理值，以便有足够的时间让测试成功完成。因此，如果计时器超时，测试将失败。以下示例通过使用定时等待 std::async 返回的 Future 来展示该方法：

\begin{cpp}
#include <gtest/gtest.h>
#include <chrono>
#include <future>

using namespace std::chrono;
using namespace std::chrono_literals;

int asyncFunc() {
    std::this_thread::sleep_for(100ms);
    return 42;
}

TEST(AsyncTest, TestTimeOut) {
    auto start = steady_clock::now();
    std::future<int> result = std::async(
                            std::launch::async,
                            asyncFunc);
    if (result.wait_for(200ms) ==
                std::future_status::timeout) {
        FAIL() << "Test timed out!";
    }

    EXPECT_EQ(result.get(), 42);

    auto end = steady_clock::now();
    auto elapsed = duration_cast<milliseconds>(
                                end - start);
    EXPECT_LT(elapsed.count(), 200);
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

现在，调用Future对象结果的 wait\_for() 函数，等待 200 毫秒让异步任务完成。由于任务将在100 毫秒内完成，因此超时不会过期。如果出于任何原因，使用低于 100 毫秒的值调用 wait\_for()，它将超时，并且将调用 FAIL() 宏，从而使测试失败。

测试继续运行并检查返回值是否为 42（如上例所示），然后检查运行异步任务所花费的时间是否小于使用的超时时间。

\mySubsubsection{12.3.3.}{测试回调}

测试回调是一项相关任务，尤其是在实现库和应用程序编程接口 (API) 时。以下示例显示如何测试已调用回调及其结果：

\begin{cpp}
#include <gtest/gtest.h>
#include <chrono>
#include <functional>
#include <iostream>
#include <thread>

using namespace std::chrono_literals;

void asyncFunc(std::function<void(int)> callback) {
    std::thread([callback]() {
        std::this_thread::sleep_for(1s);
        callback(42);
    }).detach();
}

TEST(AsyncTest, TestCallback) {
    int result = 0;
    bool callback_called = false;

    auto callback = [&](int value) {
        callback_called = true;
        result = value;
    };

    asyncFunc(callback);

    std::this_thread::sleep_for(2s);
    EXPECT_TRUE(callback_called);
    EXPECT_EQ(result, 42);
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

TestCallback 测试只是将回调定义为接受参数的 lambda 函数，此 lambda 函数通过引用捕获存储值参数的结果变量，以及默认情况下为 false ，并在调用回调时设置为 true 的 callback\_called 布尔变量。

然后，测试调用 asyncFunc() 函数，该函数会生成一个线程，等待一秒钟，然后调用回调并传递值 42。测试等待两秒钟，然后使用 EXPECT\_TRUE 宏检查回调是否已调用，并检查callback\_called 的值，以及结果是否具有预期值 42。

\mySubsubsection{12.3.4.}{测试事件驱动的软件}

第 9 章中了解了如何使用 Boost.Asio 及其事件队列来分派异步任务。在事件驱动编程中，还需要测试回调，如上例所示。可以设置测试来注入回调，并在调用后验证结果。以下示例显示如何在 Boost.Asio 程序中测试异步任务：

\begin{cpp}
#include <gtest/gtest.h>
#include <boost/asio.hpp>
#include <chrono>
#include <thread>

using namespace std::chrono_literals;

void asyncFunc(boost::asio::io_context& io_context,
               std::function<void(int)> callback) {
    io_context.post([callback]() {
        std::this_thread::sleep_for(100ms);
        callback(42);
    });
}

TEST(AsyncTest, BoostAsio) {
    boost::asio::io_context io_context;

    int result = 0;
    asyncFunc(io_context, [&result](int value) {
        result = value;
    });

    std::jthread io_thread([&io_context]() {
        io_context.run();
    });

    std::this_thread::sleep_for(150ms);
    EXPECT_EQ(result, 42);
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

BoostAsio 测试首先创建一个 I/O 执行上下文对象 io\_context，并将其与实现任务或回调的 lambda 函数一起传递给 asyncFunc() 函数以在后台运行。此回调只是将 lambda 函数捕获的结果变量的值，设置为传递给它的值。

asyncFunc() 函数仅使用 io\_context 来发布一个由 lambda 函数组成的任务，该函数在等待 100 毫秒后调用值为 42 的回调。

然后，测试只需等待 150 毫秒让后台任务完成，并检查结果值是否为 42 以将测试标记为通过。

\mySubsubsection{12.3.5.}{模拟外部资源}

如果异步代码还依赖于外部资源，例如：文件访问、网络服务器、计时器或其他模块，可能需要模拟，并避免由于资源问题而导致测试中出现不必要的故障。模拟是用于测试目的的技术，用于用虚假或简化的对象或函数替换或修改真实对象或函数的行为。这样，可以控制异步代码的输入和输出，并避免副作用或来自其他因素的干扰。

例如，测试的代码依赖于服务器，则服务器可能无法连接或执行其任务，从而导致测试失败。这些情况下，失败是由于资源问题，而不是由于正在测试的异步代码，从而导致错误且通常是暂时的失败。可以使用模仿其接口的自己的模拟类来模拟外部资源。

来看一个例子，了解如何使用模拟类并使用依赖项注入来使用该类进行测试。在此示例中，有一个外部资源 AsyncTaskScheduler，其 runTask() 方法用于执行异步任务。由于我们只想测试异步任务并消除异步任务调度程序可能产生的任何不良副作用，因此可以使用模拟 AsyncScheduler 接口的模拟类。此类是 MockTaskScheduler，继承自AsyncTaskScheduler并实现其runTask()基类方法，其中任务是同步运行的：

\begin{cpp}
#include <gtest/gtest.h>
#include <functional>

class AsyncTaskScheduler {
    public:
    virtual int runTask(std::function<int()> task) = 0;
};

class MockTaskScheduler : public AsyncTaskScheduler {
    public:
    int runTask(std::function<int()> task) override {
        return task();
    }
};

TEST(AsyncTests, TestDependencyInjection) {
    MockTaskScheduler scheduler;

    auto task = []() -> int {
        return 42;
    };

    int result = scheduler.runTask(task);
    EXPECT_EQ(result, 42);
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

TestDependencyInjection 测试只是以 lambda 函数的形式创建一个 MockTaskScheduler 对象和一个任务，并使用模拟对象通过运行 runTask() 函数来执行任务。一旦任务运行，结果将为42。

除了完整定义模拟类之外，还可以使用 gMock 库并仅模拟所需的方法。此示例展示了gMock 的实际操作：

\begin{cpp}
#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include <functional>

class AsyncTaskScheduler {
    public:
    virtual int runTask(std::function<int()> task) = 0;
};

class MockTaskScheduler : public AsyncTaskScheduler {
    public:
    MOCK_METHOD(int, runTask, (std::function<int()> task), (override));
};

TEST(AsyncTests, TestDependencyInjection) {
    using namespace testing;

    MockTaskScheduler scheduler;

    auto task = []() -> int {
        return 42;
    };

    EXPECT_CALL(scheduler, runTask(_)).WillOnce(
        Invoke(task)
    );

    auto result = scheduler.runTask(task);
    EXPECT_EQ(result, 42);
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

现在， MockTaskScheduler 也继承自 AsyncTaskScheduler，其中定义了接口，但不是重写其方法，而是使用 MOCK\_METHOD 宏，其中传递返回类型、模拟方法名称及其参数。

然后， TestMockMethod 测试使用 EXPECT\_CALL 宏定义对 MockTaskScheduler 中 runTask() 模拟方法的预期调用，该调用只会发生一次并调用 lambda 函数任务，该任务返回值 42。

该调用恰好发生在调用 scheduler.runTask() 的下一条指令中，将返回值存储在结果中。测试通过检查结果是否为预期值 42 结束。

\mySubsubsection{12.3.6.}{测试异常和失败}

异步任务并不总是成功并产生有效结果。有时可能会出错（网络故障、超时、异常等），返回错误或抛出异常是让用户了解这种情况的方法。我们应该模拟失败，以确保代码能够妥善处理这些情况。

测试错误或异常可以按照通常的方式进行，即使用 try-catch 块并使用断言或期望来检查是否抛出错误并使测试成功或失败。 GoogleTest 还提供了 EXPECT\_ANY\_THROW() 宏，可简化检查是否发生异常的过程。以下示例显示了这两种方法：

\begin{cpp}
#include <gtest/gtest.h>
#include <chrono>
#include <future>
#include <iostream>
#include <stdexcept>

using namespace std::chrono_literals;

int asyncFunc(bool should_fail) {
    std::this_thread::sleep_for(100ms);
    if (should_fail) {
        throw std::runtime_error("Simulated failure");
    }
    return 42;
}

TEST(AsyncTest, TestAsyncFailure1) {
    try {
        std::future<int> result = std::async(
                                std::launch::async,
                                asyncFunc, true);
        result.get();
        FAIL() << "No expected exception thrown";
    } catch (const std::exception& e) {
        SUCCEED();
    }
}

TEST(AsyncTest, TestAsyncFailure2) {
    std::future<int> result = std::async(
                            std::launch::async,
                            asyncFunc, true);
    EXPECT_ANY_THROW(result.get());
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

TestAsyncFailure1 和 TestAsyncFailure2 测试非常相似。两者都异步执行 asyncFunc() 函数，该函数现在接受 should\_fail 布尔参数，指示任务是否应成功并返回值 42 或失败并抛出异常。两个测试都使任务失败，不同之处在于，如果没有抛出异常， TestAsyncFailure1 将使用 F AIL() 宏，使测试失败，或者如果 try-catch 块捕获到异常，则使用 SUCCEED()，而 TestAsy ncFailure2 使用 EXPECT\_ANY\_THROW() 宏来检查在尝试通过调用其 get() 方法从未来结果中检索结果时是否发生异常。

\mySubsubsection{12.3.7.}{测试多个线程}

在 C++ 中测试涉及多个线程的异步软件时，一种常见且有效的技术是使用条件变量来同步线程。正如在第 4 章中看到的，条件变量允许线程等待某些条件满足后再继续，这使得它们对于管理线程间通信和协调至关重要。

接下来是一个例子，其中多个线程执行一些任务，而主线程等待所有其他线程完成。

首先定义一些必要的全局变量，例如：线程总数（num\_threads）、计数器（每次调用异步任务时都会增加的原子变量），以及条件变量 cv 及其关联的互斥锁 mtx，这将有助于在所有异步任务完成后解除主线程的阻塞：

\begin{cpp}
#include <gtest/gtest.h>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <iostream>
#include <mutex>
#include <syncstream>
#include <thread>
#include <vector>

using namespace std::chrono_literals;

#define sync_cout std::osyncstream(std::cout)

std::condition_variable cv;
std::mutex mtx;

bool ready = false;
std::atomic<unsigned> counter = 0;

const std::size_t num_threads = 5;
\end{cpp}

asyncTask() 函数将执行异步任务（在此示例中只需等待 100 毫秒），增加计数器原子变量并通过 cv 条件变量通知主线程其工作已完成：

\begin{cpp}
void asyncTask(int id) {
    sync_cout << "Thread " << id << ": Starting work..."
              << std::endl;
    std::this_thread::sleep_for(100ms);
    sync_cout << "Thread " << id << ": Work finished."
              << std::endl;

    ++counter;
    cv.notify_one();
}
\end{cpp}

TestMultipleThreads 测试将首先生成多个线程，每个线程将异步运行 asyncTask() 任务。然后，使用条件变量等待，该条件变量的计数器值与线程数相同，所以所有后台任务都已完成工作。条件变量使用 wait\_for() 函数设置 150 毫秒的超时时间，以限制测试可以运行的时间，但为所有后台任务成功完成留出一些空间：

\begin{cpp}
TEST(AsyncTest, TestMultipleThreads) {
    std::vector<std::jthread> threads;

    for (int i = 0; i < num_threads; ++i) {
        threads.emplace_back(asyncTask, i + 1);
    }

    {
        std::unique_lock<std::mutex> lock(mtx);
        cv.wait_for(lock, 150ms, [] {
            return counter == num_threads;
        });
        sync_cout << "All threads have finished."
                  << std::endl;
    }
    EXPECT_EQ(counter, num_threads);
}
\end{cpp}

通过检查计数器是否确实具有与num\_threads相同的值，测试完成了。

最后实现main()函数：

\begin{cpp}
int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

如前所述，程序首先通过调用::testing::InitGoogleTest() 初始化 GoogleTest 库，然后调用 RUN\_ALL\_TESTS() 来收集和运行所有测试。

\mySubsubsection{12.3.8.}{测试协程}

在 C++20 中，协程提供了一种编写和管理异步代码的新方法。可以使用与其他异步代码类似的方法测试基于协程的代码，但有一个细微的差别，即协程可以暂停和恢复。

来看一个简单协程的例子。

在第 8 章中，协程有一些样板代码来定义其promise类型和可等待方法。让我们从实现将定义协程的 Task 结构开始。

首先定义任务结构：

\begin{cpp}
#include <gtest/gtest.h>
#include <coroutine>
#include <exception>
#include <iostream>

struct Task {
    struct promise_type;
    using handle_type =
                std::coroutine_handle<promise_type>;

    handle_type handle_;

    Task(handle_type h) : handle_(h) {}
    ~Task() {
        if (handle_) handle_.destroy();
    }

    // struct promise_type definition
    // and await methods
};
\end{cpp}

在 Task 内部，定义了 promise\_type，描述了如何管理协程。此类型提供了某些预定义方法（钩子），用于控制如何返回值、如何暂停协程以及协程完成后如何管理资源：

\begin{cpp}
struct Task {
    // ...
    struct promise_type {
        int result_;
        std::exception_ptr exception_;

        Task get_return_object() {
            return Task(handle_type::from_promise(*this));
        }

        std::suspend_always initial_suspend() {
            return {};
        }

        std::suspend_always final_suspend() noexcept {
            return {};
        }

        void return_value(int value) {
            result_ = value;
        }

        void unhandled_exception() {
            exception_ = std::current_exception();
        }
    };
    // ....
};
\end{cpp}

然后，实现控制协程的暂停和恢复的方法：

\begin{cpp}
struct Task {
    // ...
    bool await_ready() const noexcept {
        return handle_.done();
    }

    void await_suspend(std::coroutine_handle<>
                            awaiting_handle) {
        handle_.resume();
        awaiting_handle.resume();
    }

    int await_resume() {
        if (handle_.promise().exception_) {
            std::rethrow_exception(
            handle_.promise().exception_);
        }
        return handle_.promise().result_;
    }

    int result() {
        if (handle_.promise().exception_) {
            std::rethrow_exception(
            handle_.promise().exception_);
        }
        return handle_.promise().result_;
    }
    // ....
};
\end{cpp}

有了 Task 结构后，定义两个协同程序，一个用于计算有效值，另一个用于引发异常：

\begin{cpp}
Task asyncFunc(int x) {
    co_return 2 * x;
}

Task asyncFuncWithException() {
    throw std::runtime_error("Exception from coroutine");
    co_return 0;
}
\end{cpp}

由于 GoogleTest 中 TEST() 宏内的测试函数不能直接作为协程，它们没有与之关联的 promise\_type 结构，所以需要定义一些辅助函数：

\begin{cpp}
Task testCoroutineHelper(int value) {
    co_return co_await asyncFunc(value);
}

Task testCoroutineWithExceptionHelper() {
    co_return co_await asyncFuncWithException();
}
\end{cpp}

有了这个，就可以实施测试了：

\begin{cpp}
TEST(AsyncTest, TestCoroutine) {
    auto task = testCoroutineHelper(5);
    task.handle_.resume();
    EXPECT_EQ(task.result(), 10);
}

TEST(AsyncTest, TestCoroutineWithException) {
    auto task = testCoroutineWithExceptionHelper();
    EXPECT_THROW({
            task.handle_.resume();
            task.result();
        },
        std::runtime_error);
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

TestCoroutine 测试使用 testCoroutineHelper() 辅助函数并传递值 5 来定义一项任务。当恢复协程时，预计它将返回双倍的值，因此返回值 10，使用 EXPECT\_EQ() 进行测试。

TestCoroutineWithException 测试使用类似的方法，现在使用 testCoroutineWithExceptionHelper() 辅助函数，该函数将在协程恢复时抛出异常。这正是在检查异常是否属于 std::runtime\_error 类型之前 EXPECT\_THROW() 断言宏内部发生的情况。

\mySubsubsection{12.3.9.}{压力测试}

通过执行压力测试可以实现竞争条件检测器。对于高度并发或多线程异步代码，压力测试至关重要。可以使用多个异步任务模拟高负载，以检查系统在压力下是否正常运行。此外，使用随机延迟、线程交错或压力测试工具来减少确定性条件、增加测试覆盖率也很重要。

下一个示例显示了压力测试的实现，该测试生成 100（total\_nums）个线程，这些线程执行异步任务，其中原子变量计数器在随机等待后每次运行都会增加：

\begin{cpp}
#include <gtest/gtest.h>
#include <atomic>
#include <chrono>
#include <iostream>
#include <thread>
#include <vector>

std::atomic<int> counter(0);
const std::size_t total_runs = 100;

void asyncIncrement() {
    std::this_thread::sleep_for(std::chrono::milliseconds(rand() %
    100));
    counter.fetch_add(1);
}

TEST(AsyncTest, StressTest) {
    std::vector<std::thread> threads;

    for (std::size_t i = 0; i < total_runs; ++i) {
        threads.emplace_back(asyncIncrement);
    }
    for (auto& thread : threads) {
        thread.join();
    }
    EXPECT_EQ(counter, total_runs);
}

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
\end{cpp}

如果计数器的值与线程总数相同，则测试成功。

\mySubsubsection{12.3.10.}{并行测试}

为了更快地运行测试套件，可以并行化在不同线程中运行的测试，但测试必须是独立的，每个测试都作为同步单线程解决方案在特定线程中运行。此外，需要设置和拆除必要的对象，而不保留以前测试运行的状态。

当将 CMake 与 GoogleTest 一起使用时，可以通过使用以下命令指定要使用的并发作业数来并行运行所有检测到的测试：

\begin{shell}
$ ctest –j <num_jobs>
\end{shell}

本节中显示的所有示例只是测试异步代码的一小部分，这些技术能够提供足够的洞察力和知识，以便开发进一步的测试技术来应对可能遇到的特定场景。











