

\mySubsubsection{7.4.1.}{Exceptions when calling std::async}
